#!/bin/bash
set -e

# for identical results, use:
# * https://github.com/obfusk/dev-misc/blob/master/vimrc
# * https://github.com/obfusk/vim-niji-1/tree/used-by-obfusk

[ $# -eq 2 ] || exit 1
from="$1" to="$2"

vim -RE +'let g:html_dynamic_folds=1' +TOhtml +"w! $to" +'qa!' "$from"

sed -i -r \
  -e $'/id=\'fold2\'/! s!class=\'closed-fold\'!class=\'open-fold\'!' \
  -e 's!.*DOCTYPE.*!<\!DOCTYPE html>!' \
  -e '/^body/ s!\}!text-align: center; }!' \
  -e '/^pre/ s!\}!text-align: left; display: inline-block; width: max-content; }!' \
  -e 's!.*<title>.*!<title>'"$(basename "$from")"'</title>!' \
  -e 's!^\*.*!html { font-size: 1.2em; }!' \
  "$to"
