#!/bin/bash
set -e

src_list () {
  grep -Eno '^\s{,4}:\S+' "$1" | \
    sed 's!\s*!!g' | sed -r 's!^([0-9]+)::(.*)!\2 \1!' | \
    grep -v ^:_ | sort | awk '!_[$1]++'
}

[ $# -eq 1 ] || [ $# -eq 2 ] || exit 1
file="$1" url="$2"

src_list "$file" | while read -r ident lineno; do
  echo "* [\`$ident\`]($url$(basename "$file").html#L$lineno)"
done
